version: '1'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build:
      context: . 
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5432:5432"