version: '1'
services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "8080:5173"
    depends_on:
      - backend
  db:
    restart: always
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5432:5432"
  reverse_proxy:
    restart: always
    build:
      context: .
      dockerfile: ./docker/reverse_proxy/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    
